In [1]:
import numpy as np

In [2]:
a = np.random.rand(100,100)

In [3]:
a

array([[0.93654232, 0.26807769, 0.77837922, ..., 0.9147933 , 0.78381619,
        0.84468909],
       [0.39846454, 0.50893048, 0.89820824, ..., 0.10726773, 0.81418328,
        0.20005087],
       [0.52353006, 0.83934653, 0.96587242, ..., 0.77866894, 0.02503011,
        0.34221688],
       ...,
       [0.63165974, 0.96218189, 0.19747074, ..., 0.24510462, 0.60832134,
        0.51155416],
       [0.32323444, 0.7088439 , 0.30444518, ..., 0.19318053, 0.47098051,
        0.91732783],
       [0.49903677, 0.27821098, 0.59820792, ..., 0.47229719, 0.877155  ,
        0.01417146]])

In [4]:
a.shape

(100, 100)

In [5]:
a = np.round(100 * a)

In [6]:
a

array([[94., 27., 78., ..., 91., 78., 84.],
       [40., 51., 90., ..., 11., 81., 20.],
       [52., 84., 97., ..., 78.,  3., 34.],
       ...,
       [63., 96., 20., ..., 25., 61., 51.],
       [32., 71., 30., ..., 19., 47., 92.],
       [50., 28., 60., ..., 47., 88.,  1.]])

In [20]:
a

array([[ 4.,  7., 31., ..., 16., 14., 54.],
       [91., 40., 70., ..., 75., 19., 99.],
       [14., 59., 87., ...,  4., 21., 12.],
       ...,
       [18., 36., 91., ..., 99., 54., 61.],
       [91., 47., 82., ..., 75., 77., 53.],
       [62., 79., 78., ...,  6., 40.,  7.]])

In [14]:
a[:30,:30] = 99

In [15]:
a

array([[99., 99., 99., ..., 91., 78., 84.],
       [99., 99., 99., ..., 11., 81., 20.],
       [99., 99., 99., ..., 78.,  3., 34.],
       ...,
       [63., 96., 20., ..., 25., 61., 51.],
       [32., 71., 30., ..., 19., 47., 92.],
       [50., 28., 60., ..., 47., 88.,  1.]])

In [8]:
list_ids = [(1,20),(11,1)]

In [9]:
nparr[list_ids]

array([99., 61.])

In [10]:
a[-1,70::2]

array([74., 56., 28., 36.,  4., 89.,  7., 31., 64., 44., 39., 23., 27.,
       93., 88.])

In [11]:
a[::2,:2:1]

array([[94., 27.],
       [52., 84.],
       [ 1., 87.],
       [43., 79.],
       [ 3., 18.],
       [46., 69.],
       [62., 16.],
       [70., 33.],
       [41., 70.],
       [33., 73.],
       [ 8., 61.],
       [50., 38.],
       [14., 26.],
       [72., 47.],
       [34., 25.],
       [20., 92.],
       [26., 89.],
       [12., 13.],
       [34., 78.],
       [12., 31.],
       [26., 16.],
       [71., 66.],
       [55., 27.],
       [92., 67.],
       [49., 90.],
       [49., 42.],
       [10., 48.],
       [78., 91.],
       [26., 70.],
       [ 1., 47.],
       [22., 17.],
       [82., 23.],
       [70., 66.],
       [48., 79.],
       [85., 67.],
       [36., 53.],
       [18.,  9.],
       [54., 42.],
       [17., 43.],
       [ 9., 52.],
       [80.,  8.],
       [52., 24.],
       [54., 84.],
       [21., 66.],
       [30., 62.],
       [31., 14.],
       [42., 41.],
       [72., 39.],
       [52., 64.],
       [32., 71.]])